Add screenshot button for videos
biigle/core pull request #1004
Opened 2024-12-06 08:23 UTC by lehecht

Closes #956.

2024-12-09 07:04 UTC, lehecht commented
@mzur 
How can I check if my button is disabled for non-CORS enabled videos? Do you know any websites that I could use to test this? Or did you use a different approach for testing?

2024-12-09 13:30 UTC, mzur commented
On your local instance you could use the [BIIGLE landing page video](https://s3.bi.denbi.de/swift/v1/BiigleAssets/BiigleLanding.mp4).

2024-12-12 15:30 UTC, mzur requested changes
I think I prefer not to use provide/inject as it hides where the data is coming from. Maybe this is a chance to refactor the screenshot button a bit so it gets all data it needs through props. E.g. if it gets the image/video ID as a prop, it does not even need the image/video changed event any more.

The `map.init` event must stay, though, as the map object must not be passed as a prop. It should never be made reactive.

2024-12-12 15:30 UTC, mzur commented on resources/assets/js/videos/videoContainer.vue
> +                });
This tries to download the whole video. Usually the video is fetched dynamically through a series of HTTP range requests, which is crucial here.

You need another method to detect CORS. Maybe create a small canvas element and try to read some data from the video into it?

2024-12-12 15:30 UTC, mzur commented on resources/assets/js/annotations/annotatorContainer.vue
> +        imageInfo['type'] = 'image';
Where do you use `type`?

2024-12-13 07:22 UTC, lehecht commented
@mzur 
> Maybe this is a chance to refactor the screenshot button a bit so it gets all data it needs through props

I also thought about it, but then I need to refactor the video and image `settingsTab`, too. The settingsTabs import the `screenshotButton`, which would then need the same properties as the `screenshotbutton`. I am not sure, if they should get props that they will not use except to pass them to the `screenshotbutton`.

2024-12-18 08:33 UTC, mzur commented
If it's not too much, I think it is fine to pass the props through the settings tab.

Alternatively you could `provide` the individual properties (e.g. current ID, current filename) instead of a single "files" object. This is at least more descriptive and you can find the location where these are coming from easier than with the generic name. This would still be better than the solution with the event.

2025-01-10 08:56 UTC, mzur requested changes

2025-01-10 08:56 UTC, mzur commented on resources/assets/js/annotations/annotatorContainer.vue
> +        this.map = this.$refs.canvas.map;
The map must not become a reactive property (see previous review). While you can replace the other use of `Event` with props, the `map.init` event listener must stay.

2025-01-10 08:56 UTC, mzur commented on resources/assets/js/annotations/components/screenshotButton.vue
> +        },
The previous name `filenames` was more descriptive.

2025-01-10 08:56 UTC, mzur commented on resources/views/annotations/show.blade.php
> +    biigle.$declare('annotations.imagesObj', {!! $images !!});
Since you only need the filenames, you can use `imagesFilenames` instead.

2025-01-10 08:56 UTC, mzur commented on resources/views/videos/show.blade.php
> +    biigle.$declare('videos.videosObj', {!! $videos !!});
Since you only need the filenames, you can use `videoFilenames` instead.

2025-01-10 08:56 UTC, mzur commented on resources/assets/js/videos/videoContainer.vue
>              });
This would be more "promise-y":

```js
let videoPromise = new Vue.Promise((resolve) => {
    this.video.addEventListener('canplay', resolve);
});
videoPromise.then(this.checkCORSProperty);
```

2025-01-16 09:15 UTC, lehecht commented on resources/assets/js/annotations/annotatorContainer.vue
> +        this.map = this.$refs.canvas.map;
Just out of curiosity, why should the map not be made a reactive property?

2025-01-16 09:49 UTC, lehecht commented on resources/views/annotations/show.blade.php
> +    biigle.$declare('annotations.imagesObj', {!! $images !!});
I need the object, because it maps the video ids to the file names. This ensures that the screenshots get the right file name.

2025-01-17 09:16 UTC, mzur commented on resources/assets/js/annotations/annotatorContainer.vue
> +        this.map = this.$refs.canvas.map;
Vue will recursively walk through the whole object (which is very large) and make everything reactive that it can find. It will hook up the reactivity watchers/getters/setters to everything. This will make the whole OpenLayers system slow. With performance-critical paths/objects like this, you have to be very careful with Vue.

2025-01-17 09:20 UTC, mzur commented on resources/views/annotations/show.blade.php
> +    biigle.$declare('annotations.imagesObj', {!! $images !!});
I still find it redundant with `imagesIds` and `imagesFilenames` just above this line. This will inflate the generated HTML of this template with duplicate information. The image annotation tool produced a screenshot with the correct filename before, too, so there should be a way to do it with the existing information (correct me if I'm wrong).

2025-01-28 11:01 UTC, mzur approved these changes
Thanks!

2025-01-28 11:01 UTC, merged

2025-02-06 18:29 UTC, davidsean commented
not sure if the disabled for non-CORS is working.
(video hosted on your s3.bi.denbi.de storage)
![image](https://github.com/user-attachments/assets/cfbf30b8-62d9-45b7-a2be-6c9199693149)
https://biigle.de/videos/33784/annotations

2025-02-07 08:30 UTC, mzur commented
@davidsean Thanks, I can confirm that. I haven't checked the cause, yet, but we'll look at it again.