Highlight settings tab when annotation opacity is 0
biigle/core pull request #1009
Opened 2024-12-11 16:34 UTC by abezine

Resolves https://github.com/biigle/core/issues/457

2024-12-12 09:07 UTC, lehecht requested changes

2024-12-12 09:07 UTC, lehecht commented on resources/assets/js/annotations/annotatorContainer.vue
> +
```suggestion
```
Please remove the new line.

2025-01-06 08:42 UTC, mzur commented
@lehecht Can you please finish this?

2025-01-10 10:45 UTC, mzur approved these changes

2025-01-10 10:45 UTC, merged