Video single frame annotation
biigle/core pull request #1019
Opened 2024-12-19 20:48 UTC by aneust

Add a settings option to the video annotation tool to automatically finish new annotations after the first frame

- Add button to settings
- Add description in manual
- Disabled "Finish" and "Track Annotation" control buttons, when option is activated
- Prevented double-click behavior for point annotations

closes #786

2025-01-06 08:42 UTC, mzur commented
@aneust Was this closed on purpose?

2025-01-06 09:31 UTC, aneust commented
@mzur Closed on purpose, Leane found some strange behavior I first could not reproduce. Think now it was caused by the settings.

2025-01-06 10:33 UTC, mzur commented
Ok, thanks. You could also keep this as a Draft PR while you keep working on the issue.

2025-01-15 08:01 UTC, lehecht requested changes

2025-01-29 07:05 UTC, lehecht requested changes

2025-01-31 06:44 UTC, lehecht reviewed
Looks good to me now. Please request a review from @mzur.

2025-01-31 10:50 UTC, mzur commented
I saw the mention and self-requested the review :wink: @lehecht You can also request the review from me when you are done.

2025-01-31 11:19 UTC, mzur reviewed
Two comments about the UI:

- The setting doesn't affect whole-frame annotations but it should.

- To be more user-friendly, the "finish annotation" and "track annotation" buttons (which are disabled) could get titles like "Disable the single-frame annotation option to create multi-frame annotations" ("Disable the single-frame annotation option to track annotations"). This way users are reminded of what to do if they want to use the buttons again. You could implement this with `v-if` showing a completely different set of buttons which are always disabled and have the new title.

Otherwise it works great. See some comments about the code below.

2025-01-31 11:19 UTC, mzur commented on resources/assets/js/videos/components/videoScreen/drawInteractions.vue
> +                    this.pendingAnnotationSource.once('addfeature', function (e) {
Please add the explanation:

```
// The feature is added to the source only after this event
// is handled, so remove has to happen after the addfeature
// event.
```

2025-01-31 11:19 UTC, mzur commented on resources/assets/js/videos/components/videoScreen/drawInteractions.vue
> +                    });
Shouldn't you return here and skip the rest of the function?

2025-01-31 11:19 UTC, mzur commented on resources/assets/js/videos/components/videoScreen/drawInteractions.vue
> +
Since `computeDistance` and the constants are used both in the image annotation tool and the video annotation tool, please create a new file for these and reuse the same function/constants in both tools.

2025-01-31 11:19 UTC, mzur commented on resources/assets/js/videos/components/videoScreen/drawInteractions.vue
> +                if (this.singleAnnotation && this.isPointDoubleClick(e)) {
Don't you have to check `this.isDrawingPoint` here, too?

2025-01-31 11:19 UTC, mzur commented on resources/assets/js/videos/components/videoScreen/drawInteractions.vue
> +            }
I feel all this can be added to the `if` above when refactored appropriately. This also would add the ´return` I asked for above.

2025-01-31 11:19 UTC, mzur commented on resources/views/videos/show/sidebar-settings.blade.php
> +                    <power-toggle :active="singleAnnotation" title-off="Enable Single-Frame Annotation" title-on="Disable Single-Frame Annotation" v-on:on="handleSingleAnnotation" v-on:off="handleDis
The title is not very helpful. What about "Enable always creating single-frame annotations" (and "Disable ...")?

2025-02-07 13:13 UTC, mzur requested changes
While the setting now affects whole frame annotations, I can't create these any more. The tool is activated but I no longer have a way to "finish" it. When the setting is activated, the whole frame annotation should be immediately created when the button is clicked.

Apart from that, only minor comments are left.

2025-02-07 13:13 UTC, mzur commented on resources/assets/js/videos/components/videoScreen.vue
> +        },
These are probably no longer required.

2025-02-11 13:43 UTC, mzur reviewed
One last general comment:

When the new settings option is active, the title text of the buttons still reads "Start a point annotation", "Start a rectangle annotation", etc. It should change to something similar to the image  annotation tool ("Set a point", "Draw a rectangle", ...).

2025-02-11 13:43 UTC, mzur commented on resources/assets/js/videos/components/videoScreen.vue
> +                            :disabled="this.cantFinishDrawAnnotation"
Please don't use `this` anywhere in this template. It works without, too: `v-if="cantFinishDrawAnnotation"`.

2025-02-12 12:22 UTC, mzur commented on resources/assets/js/videos/components/videoScreen.vue
> +                    :title="(singleAnnotation ? 'Draw a whole frame' : 'Start a whole frame annotation') + ' 𝗛'"
```suggestion
                    :title="(singleAnnotation ? 'Create a whole frame annotation' : 'Start a whole frame annotation') + ' 𝗛'"
```

2025-02-12 12:29 UTC, merged