Implement snap interaction
biigle/core pull request #793
Opened 2024-03-04 08:36 UTC by lehecht

Implements snap interaction to enable creating shapes in different 45° angles.

To activate snapping during drawing, the control key needs to be pressed once.

2024-03-05 08:33 UTC, mzur commented
Resolves #252

2024-03-05 08:48 UTC, mzur reviewed
A creative approach with the visible "guidelines"! But again, I probably should have made more clear how I envision this feature. I'll demonstrate how I think it should look with Inkscape (drawing a polygon but this also transfers to rectangles):

[Screencast from 05.03.2024 09:39:34.webm](https://github.com/biigle/core/assets/2457311/2e38f138-4cfb-4638-a02c-f59d77b75a34)

In Inkscape, while I press <kbd>Ctrl</kbd>, the line snaps to multiples of 15° (here we still want only 45°). When I click to create a new point of the line, the next line segment shows the same behavior.

The difference to the current approach is:

- There are no visible guidelines.
- I need to keep the shortcut key pressed to activate the behavior. When the key is released, the current line segment no longer snaps to the angles.
- It works individually for each line segment. Currently, the guidelines are only created for the first.

While you probably focused on rectangles with this first implementation, the behavior described above would (and should) also work on lines and polygons because the interactions are the same.

I think the current implementation is not too far off. Using guidelines and the snap interaction is the way to go. The guidelines could be made invisible and have to be updated for each new point. Then the whole thing should only be active while <kbd>Ctrl</kbd> is pressed.

2024-03-14 06:53 UTC, lehecht commented
@mzur 
I noticed that the snapping not only occurs for the guidlines but also for other annotations. Is this a problem that needs to be fixed?

2024-03-14 08:48 UTC, mzur commented
> I noticed that the snapping not only occurs for the guidlines but also for other annotations. Is this a problem that needs to be fixed?

Yes. You can use the [`source` option](https://openlayers.org/en/v5.3.0/apidoc/module-ol_interaction_Snap-Snap.html) of the snap interaction to control this.

2024-03-19 07:50 UTC, lehecht commented
@mzur 
Is there a reason why you declared [this function](https://github.com/biigle/core/blob/662e38e4c92e9bb2c72ce133dfb628451c804b88/resources/assets/js/annotations/components/annotationCanvas/drawInteractions.vue#L17-L25) not as vue-method? I'm currently fixing a bug and the solution could be either to make this function a vue-method, in order to change a data property there, or to use a separate shift-key-event listener in the created method.

2024-03-19 08:13 UTC, mzur commented
> Is there a reason why you declared [this function](https://github.com/biigle/core/blob/662e38e4c92e9bb2c72ce133dfb628451c804b88/resources/assets/js/annotations/components/annotationCanvas/drawInteractions.vue#L17-L25) not as vue-method?

Only that there was no need for it before. You can implement it as a Vue method, too.

2024-03-27 10:03 UTC, lehecht commented
Note: My last bug fix only works when biigle/openlayers#5 is merged.

2024-04-10 07:51 UTC, mzur requested changes
We are getting there!

It seems like I have to press <kbd>Ctrl</kbd> before drawing the first point of the annotation to enable this feature. Can you change this so I can press the key anytime (even after the first point) and the feature is enabled?

Can you also increase the `pixelTolerance` of the snap interaction to maybe 15 or so?

2024-05-17 05:52 UTC, lehecht commented on resources/assets/js/annotations/snapInteraction.vue
> +            this.snapInteraction = new Snap({ source: this.annotationSource, features: new Collection(this.snapLineFeatures) });
When I delete the annotationSource and feature styling, the snap lines are still visible. Did you just remove the annotation Source from line 95 or did you do also something else?

2024-05-17 06:11 UTC, lehecht commented
> It seems like I have to press Ctrl before drawing the first point of the annotation to enable this feature. Can you change this so I can press the key anytime (even after the first point) and the feature is enabled?

I don't exactly know what you mean. When I create the first point and press Ctrl afterwards, I can use the tool without problems. But I need to say that the old and smaller pixelTolerance made it a bit more difficult to distinguish if that tool was active or not.

2024-05-17 10:28 UTC, mzur commented
> When I create the first point and press Ctrl afterwards, I can use the tool without problems.

You are right. Maybe I didn't notice the snapping for some reason...

Can you please also add something to the keyboard shortcuts manual articles (image and video)? Then I'll do my final review but everything looks good so far!

2024-05-21 12:10 UTC, mzur reviewed
The feature is perfect :ok_hand: I've just commented on some minor things regarding the code. Also, I've updated the manual articles a little, as I found that the shortcut should be moved to a separate "section" there.

2024-05-21 12:32 UTC, mzur commented
Here is also a follow-up issue: https://github.com/biigle/core/issues/836

2024-05-23 10:24 UTC, lehecht commented on resources/assets/js/annotations/components/annotationCanvas/drawInteractions.vue
> +        }
My current approach looks like this:
```
window.addEventListener('click', (e) => {
            if(this.drawInteraction?.getActive() && this.drawInteraction?.sketchCoords_?.length > 0){
                this.shouldSnap = e.ctrlKey;
                let idx = this.drawInteraction.sketchCoords_.length - 2;
                this.snappingCoords = this.drawInteraction.sketchCoords_[idx];
            }
        });
```

2024-05-28 09:35 UTC, mzur approved these changes
Great, thanks!

2024-05-28 09:35 UTC, merged