truncates long image names in the navbar/content
biigle/core pull request #889
Opened 2024-07-23 13:49 UTC by dlangenk

Fixes #240. As I couldn't figure out how you trimmed the image filename in the annotation navbar, I used the php mb_strimwidth function. In the content the width fits exactly if you would use a resolution of 1024 x 768.

2024-07-23 14:20 UTC, mzur requested changes
Sorry but this should be done with CSS (`text-overflow: ellipsis`). This will adjust to the available space.

2024-07-24 09:05 UTC, dlangenk commented
This was far more difficult than I expected. But it works now. Not sure about if the navbar is ok like this. I tried to use the breadcrump component but failed. Probably we can have a look tomorrow how to best debug such a thing.

2024-07-24 09:49 UTC, mzur commented
If you want something easy, pick one of the "difficulty 1" [tasks](https://github.com/orgs/biigle/projects/4/views/9) :smiley:

I'll wrap this up after lunch.

2024-07-24 10:55 UTC, mzur approved these changes

2024-07-24 12:26 UTC, merged