Replace assertEquals by assertSame
biigle/core pull request #906
Opened 2024-08-19 08:02 UTC by lehecht

Use strong checks for better testing.

2024-08-20 06:10 UTC, lehecht commented
@mzur 
I overlooked a few files. I'll message you once I'm done here.

2024-08-20 07:08 UTC, lehecht commented
@mzur 
The code is ready to be reviewed.

2024-08-20 07:24 UTC, mzur commented
I'll have a look. Please work on the open [tasks](https://github.com/orgs/biigle/projects/4/views/9) first before starting something else 😉

2024-08-21 09:21 UTC, mzur requested changes

2024-08-21 09:21 UTC, mzur commented on tests/php/Http/Controllers/Api/ProjectInvitationControllerTest.php
> +        $this->assertSame($timestamp->toDateTimeString(), $invitation->expires_at->tz($timestamp->timezone)->toDateTimeString());
Just keep `assertEquals` for simplicity here.

2024-08-21 09:21 UTC, mzur commented on tests/php/Http/Controllers/Api/Volumes/MetadataControllerTest.php
> +        $this->assertSame(180, intval($jpg->metadata['yaw']));
Please update the metadata code so these values are actually stored as int/float.

2024-08-21 09:21 UTC, mzur commented on tests/php/Jobs/CreateNewImagesOrVideosTest.php
> +        $this->assertSame(180, intval($image->metadata['yaw']));
Same as above.

2024-08-21 09:21 UTC, mzur commented on tests/php/Jobs/ProcessNewImageTest.php
> +        $this->assertSame(2.6, floatval($image->metadata['area']));
Same as above.

2024-08-21 09:21 UTC, mzur commented on tests/php/Jobs/ProcessNewVideoTest.php
> +        $this->assertSame(10, intval($video->fresh()->duration));
Please update the code so the duration is always returned as float.

2024-08-21 09:21 UTC, mzur commented on tests/php/Services/Auth/ApiGuardTest.php
> +        $this->assertSame($token->updated_at->toDateTimeString(), $token->fresh()->updated_at->toDateTimeString());
Keep using `assertEquals` for simplicity.

2024-08-29 07:04 UTC, mzur approved these changes

2024-08-29 07:04 UTC, merged